### ISSUE TITLE
Snowowl on Kubernetes

### ISSUE THREAD

**Issue by hugopicq** [b2ihealthcare/snow-owl#1355]
Hello,

I recently deployed snowowl on Kubernetes alongside an Elasticsearch instance and tried to import SNOMED-CT following the tutorial in the docs but I can't finish the import properly. I tried 2 different configurations:

### Snowowl with ES as a sidecar

I first tried to deploy snowowl with ES running as a sidecar, following the docker-compose example. However, at one point in the import (~a few hours after it started) the snowowl service would stop answering without any error message and I would need to restart the pod. Then I would get the job as "running" without any error and it would stay "running" without anything happening.

Here is the configuration for the deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowowl
  labels:
    app: snowowl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowowl
  template:
    metadata:
      labels:
        app: snowowl
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: sysctl
          image: busybox:1.28
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
        - name: snowowl
          image: b2ihealthcare/snow-owl-oss:9.4.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /snowowl/info?pretty
              port: 8080
          env:
            - name: SO_JAVA_OPTS
              value: "-Xms6g -Xmx6g"
            - name: ELASTICSEARCH_URL
              value: "http://localhost:9200"
          volumeMounts:
            - name: snowowl-config
              mountPath: /etc/snowowl/snowowl.yml
              subPath: snowowl.yml
              readOnly: true
            - name: elastic-data
              mountPath: /var/lib/snowowl/resources/indexes
          resources:
            requests:
              cpu: "2000m"
              memory: "7Gi"
            limits:
              cpu: "3000m"
              memory: "7Gi"
        - name: elastic-snowowl
          image: elasticsearch:8.15.1
          ports:
            - containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms4g -Xmx4g
          volumeMounts:
            - name: elastic-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: elastic-config
              mountPath: /usr/share/elasticsearch/config/analysis/synonym.txt
              subPath: synonym.txt
              readOnly: true
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: "2000m"
              memory: "7Gi"
            limits:
              cpu: "3000m"
              memory: "7Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: elastic-config
          configMap:
            name: snowowl-elastic-config
        - name: snowowl-config
          configMap:
            name: snowowl-config
        - name: elastic-data
          persistentVolumeClaim:
            claimName: snowowl-data
```

And here the elastic configuration:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: snowowl-elastic-config
data:
  elasticsearch.yml: |
    cluster.name: "elastic-snowowl"
    node.name: "elastic-snowowl"
    discovery.type: "single-node"
    rest.action.multi.allow_explicit_index: "false"
    http.type: "netty4"
    http.cors.enabled: "true"
    http.cors.allow-origin: "/https?:\\/\\/localhost(:[0-9]+)?/"
    search.max_buckets: 1500000
    network.host: 0.0.0.0
    index.store.preload: ["dvd", "nvd"]
    xpack.security.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
    ingest.geoip.downloader.enabled: false
    indices.lifecycle.history_index_enabled: false
    slm.history_index_enabled: false
    cluster.deprecation_indexing.enabled: false
    stack.templates.enabled: false
  synonym.txt: |
 
```

### Snowowl separated from ES

I also tried to deploy snowowl and ES as 2 separate pods. In this configuration, I don't get the snowowl service liveness problem, but the import job stays in the "running" state after 6 days of import... The elastic configuration is the same as above but here are the deployment files for snowowl and ES : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowowl
  labels:
    app: snowowl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowowl
  template:
    metadata:
      labels:
        app: snowowl
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: sysctl
          image: busybox:1.28
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
        - name: snowowl
          image: b2ihealthcare/snow-owl-oss:9.4.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /snowowl/info?pretty
              port: 8080
          env:
            - name: SO_JAVA_OPTS
              value: "-Xms4g -Xmx4g"
            - name: ELASTICSEARCH_URL
              value: "http://snowowl-elastic.ps-production-apps.svc.cluster.local:9200"
          volumeMounts:
            - name: snowowl-config
              mountPath: /etc/snowowl/snowowl.yml
              subPath: snowowl.yml
              readOnly: true
            - name: snowowl-data
              mountPath: /var/lib/snowowl/resources
          resources:
            requests:
              cpu: "2000m"
              memory: "6Gi"
            limits:
              cpu: "3000m"
              memory: "6Gi"
      volumes:
        - name: snowowl-config
          configMap:
            name: snowowl-config
        - name: snowowl-data
          persistentVolumeClaim:
            claimName: snowowl-data
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowowl-elastic
  labels:
    app: snowowl-elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowowl-elastic
  template:
    metadata:
      labels:
        app: snowowl-elastic
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: sysctl
          image: busybox:1.28
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
        - name: snowowl-elastic
          image: elasticsearch:8.15.1
          ports:
            - containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms4g -Xmx4g
          volumeMounts:
            - name: elastic-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: elastic-config
              mountPath: /usr/share/elasticsearch/config/analysis/synonym.txt
              subPath: synonym.txt
              readOnly: true
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: "2000m"
              memory: "7Gi"
            limits:
              cpu: "3000m"
              memory: "7Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: elastic-config
          configMap:
            name: snowowl-elastic-config
        - name: elastic-data
          persistentVolumeClaim:
            claimName: snowowl-elastic-data
```

As I don't have any error in the logs, I don't have much to debug.
- Do you have any idea what the problem could be?
- Does the configuration seem alright?
- Do you have a recommandation for snowowl deployment between both patterns?
