### ISSUE TITLE
How to Resolve CORS Issues in Snow Owl Docker Compose Setup

### ISSUE THREAD

**Issue by HengJayWang** [b2ihealthcare/snow-owl#1370]
Dear Snow Owl Developers,

Hello, I'm a new developer exploring Snow Owl. I have successfully run the Snow Owl service using the docker-compose.yml file.

My Snow Owl instance is running on a GCP VM, and the URL is assumed to be https://snow-owl.server/. Another frontend website (URL: https://frontend.website.org) interacts with the Snow Owl API to fetch SNOMED CT-related data. However, I encountered Cross-Origin Resource Sharing (CORS) errors on the frontend website, with the error message saying: "Ensure CORS response header values are valid."

I tried to find solutions regarding CORS settings in [the official Snow Owl documentation](https://docs.b2ihealthcare.com/snow-owl/setup-and-administration) but couldn't find any relevant information. So, I searched for the keyword "CORS" in this GitHub repository and noticed that there are some CORS settings in the `docker/compose/config/elasticsearch/elasticsearch.yml` file:

```
http.cors.enabled: "true"
http.cors.allow-origin: "/https?:\\/\\/localhost(:[0-9]+)?/"
```

Based on [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-cors.html) and [some discussions](https://stackoverflow.com/questions/54697423/how-to-resolve-cors-issues-when-querying-elasticsearch), I corrected the true typo and modified the settings as follows:

```
http.cors.enabled: true
http.cors.allow-origin: "/https?:\\/\\/localhost(:[0-9]+)?/"
http.cors.allow-methods: GET, POST, PUT, DELETE, OPTIONS
http.cors.allow-headers: X-Requested-With, Content-Type, Content-Length, Authorization
http.cors.allow-credentials: true
```

After making these changes, I restarted the service using `docker compose restart elasticsearch`, but I still encountered the same CORS error on my frontend website. 🥲

Additionally, I tried adding CORS settings to the `docker/compose/config/snowowl/snowowl.yml` file:

```
(original content)

http:
  cors:
    enabled: true
    allowed-origins: 
      - "https://frontend.website.org"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
    allow-credentials: true
    max-age: 3600
```

Similarly, after updating the file, I restarted the service using docker compose restart snowowl, but the same CORS error persisted on my frontend website again. 🫠

💡 My Questions:

1. Given my situation, is it possible to resolve the CORS issue for frontend-backend API integration by configuring the compose/config/snowowl/snowowl.yml or compose/config/elasticsearch/elasticsearch.yml files after the services are run using docker-compose? Or is this approach entirely incorrect and unfeasible?

2. If it is possible to configure these two YAML files to resolve the CORS issue, what should the correct settings be? Are there any documents or examples I can refer to? I am unsure if my current settings are correct, especially regarding the allowed-origins URL. Should it be the backend service URL `https://snow-owl.server/` or the frontend website URL `https://frontend.website.org/` ? I am not familiar with backend development, so if there are clear and precise documents, please provide them for my reference. Thank you. 🙏🥰
